# Generated by Django 4.0.5 on 2022-07-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_sales_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_view_client', 'Can view client'),)},
        ),
    ]
